### ISSUE TITLE
spike: investigate LLVM vectorization and integration with RV

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11163]
The task here is to continue to investigate how Chapel can be integrated with the Region Vectorizer.

Initial work is here:

https://github.com/mppf/chapel/tree/rv

* done: probably want the vector width to be the maximum vector width of the target
* critical sections can be outlined into separate functions but RV will need metadata hints to not give up on them (https://github.com/cdl-saarland/rv/wiki/Critical-sections)
* follow other steps here: https://github.com/cdl-saarland/rv/wiki/How-to-use-RV%27s-outer-loop-vectorizer-in-your-LLVM-frontend
* start to develop a plan for hinting custom reductions to RV #11637

**Comment by mppf** [comment]
I was getting a core-dump when trying to compile the clenshaw benchmark with RV... that needs to be investigated.

**Comment by simoll** [comment]
That's fixed by https://github.com/cdl-saarland/rv/commit/54b0bf5efe077fb7e1408b41dcd82a54fecc8836
Feel free to open new issues on the RV github if you encounter bugs.

I do see a double-free for that benchmark though (with or without RV): `double free or corruption (fasttop)`. I am on LLVM 6 without the two patches that ship with Chapel.

**Comment by mppf** [comment]
@simoll - Thanks for your help but I'm still seeing it fail within RV.

I've fixed the version of clenshaw above to not have a double free. (There was a language change).

With my rv branch, I run: `chpl clenshaw.chpl --fast --llvm --vectorize ` and I'm getting a seg fault along these lines:

```
llvm::BasicBlock::getTerminator() const ()
rv::LoopCloner::CloneLoop(llvm::Loop&, llvm::ValueMap<llvm::Value const*, llvm::WeakTrackingVH, llvm::ValueMapConfig<llvm::Value const*, llvm::sys::SmartMutex<false> > >&) ()
v::CloneLoop(llvm::Loop&, llvm::Function&, llvm::DominatorTree&, llvm::PostDominatorTree&, llvm::LoopInfo&, llvm::BranchProbabilityInfo*, llvm::ValueMap<llvm::Value const*, llvm::WeakTrackingVH, llvm::ValueMapConfig<llvm::Value const*, llvm::sys::SmartMutex<false> > >&) ()
rv::RemainderTransform::createVectorizableLoop(llvm::Loop&, std::set<llvm::Value*, std::less<llvm::Value*>, std::allocator<llvm::Value*> >&, int, int) ()
rv::LoopVectorizer::transformToVectorizableLoop(llvm::Loop&, int, int, std::set<llvm::Value*, std::less<llvm::Value*>, std::allocator<llvm::Value*> >&) ()
rv::LoopVectorizer::vectorizeLoop(llvm::Loop&) ()
```

I can figure out more, but I don't have a debug build of LLVM+RV at the moment.

Thanks for your help!

**Comment by mppf** [comment]
I pushed updates to my RV branch. I really need to add a command line flag for it.

**Comment by mppf** [comment]
@simoll - I got it working. I had to adjust the Chapel compiler to call rv::addPreparatoryPasses(PM); rv::addWholeFunctionVectorizer(PM); rv::addOuterLoopVectorizer(PM); rv::addCleanupPasses(PM);. Before we were just calling rv::addOuterLoopVectorizer(PM);.

See https://github.com/cdl-saarland/rv/issues/30 for some requests to make this easier for the next person.

**Comment by mppf** [comment]
Note that the LLVM LoopVectorizer could be taught about custom reductions too, it views these as a kind of recurrence, so it's RecurrenceDescriptor that would need to be updated.

**Comment by mppf** [comment]
TODOs from this issue need new issues
Needs issue: npb/is/diten/is_no_buckets, npb/is/diten/is seems to be getting wrong output

**Comment by mppf** [comment]
I've closed this issue but there is lots of future work:

* merging PR #11673 
* Investigate testing failures with RV vectorization #11679
* RV integration emits "loop not vectorized" warnings/remarks #11678
* Clenshaw is not vectorizing with RV - issue #11636.
* improve vectorization hinting: complex reductions #11637
