### ISSUE TITLE
Incorrect documentation for string.strip function.

### ISSUE THREAD

**Issue by tmacd8** [chapel-lang/chapel#16701]
### Summary of Problem
The online documentation for string function strip uses ```string.strip(chars: string = " trn"``` but should use ```\t\r\n``` instead.

### Configuration Information

- Output of `chpl --version`:
chpl version 1.23.0
Copyright 2020 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: none
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**Comment by Venkatavaradan-R** [comment]
This issue seems to have been fixed. I think it should be closed. 
@lydia-duncan

**Comment by tmacd8** [comment]
When I view web page:  `https://chapel-lang.org/docs/builtins/String.html?highlight=strip#String.string.strip` I still see the problem ('trn' instead of '\t\r\n') using browsers firefox, chrome, and brave on Ubuntu 20.04.2 and Windows 10.

**Comment by Venkatavaradan-R** [comment]
Hmm, weird. 
The latest doc renders of the master branch show that it has been fixed.

I compiled and ran `make docs` on my system and the docs generated don't have this issue.
Screenshot:
![Screenshot from 2021-03-13 22-51-13](https://user-images.githubusercontent.com/44594675/111038399-a83fc880-844e-11eb-9337-401b73404f85.png)

It looks like it's not been pushed to wherever the websites actually being hosted.

**Comment by bradcray** [comment]
I agree that this has been fixed, thanks for pointing it out @Venkatavaradan-R .  I believe that the difference between what you're seeing is that @tmacd8 is referring to the documentation from the last release: https://chapel-lang.org/docs/builtins/String.html#String.string.strip   Whereas the docs for the development branch and upcoming release are fixed:  https://chapel-lang.org/docs/1.24/builtins/String.html#String.string.strip
