### ISSUE TITLE
Compilation failure for bulk-transfer involving rank-changed Block

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7063]
### Summary of Problem
Array assignment between two Block-distributed arrays where one array is rank-changed results in a compilation failure with an error message like this:

```
$CHPL_HOME/modules/dists/BlockDist.chpl:1533: In function 'doiBulkTransferFrom':
$CHPL_HOME/modules/dists/BlockDist.chpl:1546: error: unresolved access of '[domain(4,int(64),false)] LocBlockDom(4,int(64),false)' by '(2*int(64))'
```

**Associated Future Test(s):**
[`test/arrays/rankChange/distRankChangeAssign.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/arrays/rankChange/distRankChangeAssign.chpl
          ) #7060

**Comment by benharsh** [comment]
Resolved by #7285

**Comment by bradcray** [comment]
Hi @benharsh: I only just noticed that the program which originally led me to this bug still isn't working, though I haven't had a chance to determine what the difference between the program and the future is.  The full program needs to be dropped into `test/distributions/robustness/arithmetic/performance/multilocale/` and is:

```chapel
use driver_domains;

const bigDom4D = Dom4D.expand((1,1,1,1));
var A: [bigDom4D] 4*int = {(...bigDom4D.dims())};
const BD = {1..n4, 1..n4} dmapped Block({1..n4, 1..n4});
var B: [BD] 4*int;

resetCommDiagnostics();
startCommDiagnostics();
B = A[1..n4,1,n4,1..n4];
stopCommDiagnostics();
writeln(getCommDiagnostics());
```

**Comment by benharsh** [comment]
Is this under gasnet? Did you run with a specific distType?

**Comment by bradcray** [comment]
No, I was only just realizing that it's specific to `CHPL_COMM=none` and no specific distType:

```
chpl -o assignRankChange --cc-warnings -M../.. --fast assignRankChange.chpl
```

**Comment by benharsh** [comment]
#7398 should keep us afloat until the bulk-transfer redesign is complete.
