### ISSUE TITLE
leak in string.reinitString()

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#7549]
### Summary of Problem

When ``string.reinitString()`` is called with ``needToCopy=false``, the
caller is handing off ownership of the ``buf``.  But if the string
already had ``this.owned==false``, the reinitialized string will also
have ``this.owned==false``, since ``reinitString()`` doesn't set it to
true in this case.

Details below the example.

### Steps to Reproduce

**Source Code:**

```chapel
var s = "1" * 8;

on Locales[numLocales-1] {

  var t = "1" * 12;
  var tx = t.localize(); // gets tx.owned == false

  writeln(tx);

  // Since s is on locale 0 and here is numLocales-1, proc =()'s 
  // helpMe() goes down the "remote copy" path calling reinitString()
  // with needToCopy=false.
  tx = s;

  writeln(tx);
}
```

**Compile command:**
chpl leaky-localize.chpl

**Execution command:**

```
./leaky-localize -nl 2 --memLeaks
111111111111
11111111

============================================================================================================================================
Allocated Memory (Bytes)                                    Number   Size     Total    Description                      Address             
============================================================================================================================================
$CHPL_HOME/modules/internal/LocaleModelHelpMem.chpl:53      1        9        9        _ic_these__ref_list_BaseArr      0x00007fc10860f0d0  
============================================================================================================================================


=================================================================================================================
Allocated Memory (Bytes)         Number   Size     Total    Description                      Address             
=================================================================================================================
=================================================================================================================
```

**Associated Future Test(s):**

No future yet.  The above reproduces the problem, but I don't know how
to express it as a memory leak future.  And it seems like it should go
with a larger set of tests of string.localize(), which I can't find.

**Details:**

```chapel
    proc ref reinitString(buf: bufferType, s_len: int, size: int,
                          needToCopy:bool = true) {
      if this.isEmptyString() {
        if (s_len == 0) || (buf == nil) then return; // nothing to do
      }

      // If the this.buff is longer than buf, then reuse the buffer if we are
      // allowed to (this.owned == true)
      if s_len != 0 {
        if needToCopy {
	  ...
        } else {
          if this.owned && !this.isEmptyString() then
            chpl_here_free(this.buff);
          this.buff = buf;
          this._size = size;
	  // XXX1 this.owned = true; ?
        }
      } else {
        // s_len == 0 so the source string is empty
        // free the old buffer
        if this.owned && !this.isEmptyString() then chpl_here_free(this.buff);
        this.buff = nil;
        this._size = 0;
	// XXX2
      }

      this.len = s_len;
    }
```

I'm sort of feeling my way through the code, so I'll note one
conclusion I've jumped to without being sure of:

When ``!needToCopy``, the caller is always passing ownership of
``buf`` to ``reinitString``.  I think this because ``proc =()``
``helpMe()`` allocates ``remote_buf``, passes it to
``reinitString(needToCopy=false)``, and keeps no other reference to
it.  So I presume that has to be the pattern whenever
``needToCopy=false`` is passed.

I'm also not sure if the test case I wrote is valid.  Is it legal to
assign to a string that's the result of ``.localize()``?

[ edit 12/5 cassella to note: This XXX2 part was fixed by #7918 ]

Also, I think there's another leak at ``// XXX2`` above, if it's valid
to have ``s_len == 0`` but ``size > 0`` (and ``buff != nil``), and for
``needToCopy`` to be ``false``.  Again the caller is handing off
ownership of ``buf``, but this path just drops it on the floor.

(I don't know if that combination of arguments is valid.  If it is,
the function leaks. If it's not, the function could probably be
simplified.)

### Configuration Information

```
fortytwo@magrathea:~/src/chpl$ chpl --version
chpl Version 1.17.0 pre-release (3b08ee5)
Copyright (c) 2004-2017, Cray Inc.  (See LICENSE file for more details)
fortytwo@magrathea:~/src/chpl$ printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none
fortytwo@magrathea:~/src/chpl$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
```

**Comment by cassella** [comment]
@mppf @benharsh this is where I ended up with the issues we discussed offline.

**Comment by cassella** [comment]
After #7754, the leak report for this test changed:


```
============================================================================================================================================
Allocated Memory (Bytes)                                    Number   Size     Total    Description                      Address             
============================================================================================================================================
$CHPL_HOME/modules/internal/LocaleModelHelpMem.chpl:53      1        9        9        remote string copy               0x00007faabf40f0d0  
============================================================================================================================================
```

```
fortytwo@magrathea:~/src/chpl$ chpl --version
chpl Version 1.17.0 pre-release (5b1ad7a)
```

I still don't know how or if to create a multilocale-only memory leak
future for this.

**Comment by mppf** [comment]
This leak no longer occurs for me on master. I think it might have been fixed by PR #7918.

**Comment by cassella** [comment]
It still fails for me on this morning's master (with -nl 2),


```
fortytwo@magrathea:~/src/chpl$ chpl --version
chpl version 1.17.0 pre-release (2da2709)
```

```
fortytwo@magrathea:~/src/chpl$ ./leaky-localize -nl 2 --memLeaks
111111111111
11111111
...
================================================================================================================================
Allocated Memory (Bytes)                        Number   Size     Total    Description                      Address
================================================================================================================================
$CHPL_HOME/modules/internal/String.chpl:115     1        9        9        remote string copy               0x00007faf96035010
================================================================================================================================
```

**Comment by mppf** [comment]
Ah, I think I missed the -nl 2 part.

**Comment by cassella** [comment]
I finally tested the change I proposed at `XXX1` above.  It segfaults
pretty good on a gasnet build, but passes valgrind cleanly with
`CHPL_COMM=none`.

```
[0] #5  <signal handler called>
[0] #6  __GI___pthread_mutex_lock (mutex=mutex@entry=0x10102464c458f) at ../nptl/pthread_mutex_lock.c:67
[0] #7  0x0000000000569737 in chpl_je_malloc_mutex_lock (tsdn=0x7fb2fbbff630, mutex=0x10102464c458f) at /home/fortytwo/src/chapel/third-party/jemalloc/jemalloc-src/include/jemalloc/internal/mutex.h:101
[0] #8  chpl_je_arena_dalloc_large (tsdn=0x7fb2fbbff630, arena=0x10102464c457f, chunk=0x400000, ptr=0x5dabb5) at /home/fortytwo/src/chapel/third-party/jemalloc/jemalloc-src/src/arena.c:3075
[0] #9  0x0000000000406a22 in chpl_free ()
[0] #10 0x0000000000406c98 in chpl_mem_free ()
[0] #11 0x0000000000461cf8 in chpl_here_free ()
[0] #12 0x0000000000419b65 in on_fn64 ()
[0] #13 0x00000000004199b7 in deinit39 ()
[0] #14 0x000000000041d66b in on_fn65 ()
[0] #15 0x000000000041d866 in find ()
[0] #16 0x00000000004107c3 in _do_command_line_cast2 ()
[0] #17 0x000000000041679c in _command_line_cast4 ()
[0] #18 0x0000000000466ad1 in chpl__init_ChapelNumLocales ()
[0] #19 0x0000000000462056 in chpl__init_LocaleModelHelpSetup ()
[0] #20 0x0000000000461514 in chpl__init_LocaleModelHelpFlat ()
[0] #21 0x000000000042e0b6 in chpl__init_LocaleModel ()
[0] #22 0x00000000004188a5 in chpl__init_ChapelStandard ()
```
